import React, { useState, useMemo, type ChangeEvent } from "react";

// Define the type for the props
interface CollegeSearchComboboxProps {
  // Use string[] or ReadonlyArray<string> to match the type of your college list
  allowedColleges: ReadonlyArray<string>;
  name: string;
  value: string;
  onChange: (e: { target: { name: string; value: string } }) => void;
  className: string;
  required: boolean;
}
// Your existing list of colleges (example)
const ALLOWED_COLLEGES = [
  "IIT MADRAS",
  "IIT DELHI",
  "IIT BOMBAY",
  "IIT KHARAGPUR",
  "IIT KANPUR",
  "IIT ROORKEE",
  "IIT GUWAHATI",
  "IIT HYDERABAD",
  "NIT TIRUCHIRAPPALLI",
  "JADAVPUR UNIVERSITY",
  "VIT VELLORE",
  "NIT ROURKELA",
  "IIT BHU VARANASI",
  "IIT (ISM) DHANBAD",
  "IIT INDORE",
  "ANNA UNIVERSITY CHENNAI",
  "IIT BHUBANESWAR",
  "BITS PILANI",
  "TIET PATIALA",
  "IIT PATNA",
  "AMRITA VISHWA VIDYAPEETHAM",
  "IIEST SHIBPUR",
  "IIT MANDI",
  "NIT SURATHKAL",
  "SOA BHUBANESWAR",
  "MIT MANIPAL",
  "IIT GANDHINAGAR",
  "IIT ROPAR",
  "IIT TIRUPATI",
  "IIT BHILAI",
  "SRM IST CHENNAI",
  "IIT JAMMU",
  "IIT GOA",
  "DTU DELHI",
  "NIT CALICUT",
  "VNIT NAGPUR",
  "KPRIT COIMBATORE",
  "K. RAMAKRISHNAN C.O.E.",
  "PDEU GANDHINAGAR",
  "VELS INSTITUTE CHENNAI",
  "IIITDM KANCHEEPURAM",
  "CIT COIMBATORE",
  "MAKAUT KOLKATA",
  "PSGIET COIMBATORE",
  "CGC LANDRAN, MOHALI",
  "TCE MADURAI",
  "AMITY UNIV. GURUGRAM",
  "RAJALAKSHMI C.O.E.",
  "NMIMS MUMBAI",
  "VJTI MUMBAI",
  "CUSAT KOCHI",
  "NIT HAMIRPUR",
  "CHENNAI INST. OF TECH",
  "NIT MANIPUR",
  "NIT MIZORAM",
  "NIT UTTARAKHAND",
  "NIT JAMSHEDPUR",
  "NIRMA UNIV. AHMEDABAD",
  "KARUNYA INST. OF TECH",
  "MAHINDRA UNIV.",
  "UCE HYDERABAD",
  "NIT GOA",
  "IIIT GWALIOR",
  "GITAM UNIV. VISAKHAPATNAM",
  "NITTET MEENAKSHI INST.",
  "JIIT NOIDA",
  "NORTHCAP UNIV. GURGAON",
  "GALGOTIAS UNIV.",
  "PES UNIVERSITY BANGALORE",
  "PANJAB UNIVERSITY",
  "SHARDA UNIV. GREATER NOIDA",
  "HITS CHENNAI",
  "SRI SAIRAM C.O.E.",
  "NIET NOIDA",
  "MEPC SCHLENK C.O.E.",
  "NIT ARUNACHAL PRADESH",
  "NIT DHARWAD",
  "AMITY UNIV. JAIPUR",
  "AMITY UNIV. KOLKATA",
  "MIT WPU PUNE",
  "KOIT GROUP",
  "GRRIET HYDERABAD",
  "KPRIT COIMBATORE",
  "KONGU C.O.E.",
  "MRIIRS FARIDABAD",
  "JNTU KAKINADA",
  "CET TRIVANDRUM",
  "PICT PUNE",
  "RVCE BANGALORE",
  "BMSCE BANGALORE",
  "RIT BANGALORE",
  "PSGTECH COIMBATORE",
  "BIT MESRA",
  "IIIT HYDERABAD",
  "IIIT BANGALORE",
  "B. S. ABDUR RAHMAN CRESCENT INST.",
  "ANURAG UNIV.",
  "CHITKARA UNIV.",
  "CMRIT BENGALURU",
  "DAIICT GANDHINAGAR",
  "G. L. A. UNIV.",
  "G. H. RAISONI C.O.E. NAGPUR",
  "IIIT GUWAHATI",
  "IGDTUW DELHI",
  "IARE HYDERABAD",
  "J. C. BOSE UNIV. YMCA",
  "JNTU ANANTAPURAMU",
  "KLE TECH UNIV.",
  "KCT COIMBATORE",
  "MMU AMBALA",
  "MANUU HYDERABAD",
  "NEW HORIZON C.O.E.",
  "NMAMIT",
  "NERIST ITANAGAR",
  "RMK C.O.E.",
  "SMVDU",
  "SONA C.O.E.",
  "SRI KRISHNA C.O.E.",
  "VARDHAMAN C.O.E.",
  "VSSUT BURLA",
  "VRSEC VIJAYAWADA",
  "VIGNAN INST. OF TECH",
  "YCCE NAGPUR",
  "ABES C.O.E. GHAZIABAD",
  "ADITYA C.O.E. SURAMPALEM",
  "ADITYA INST. OF TECH TEKKALI",
  "ARMY INST. OF TECH PUNE (AIT)",
  "SPIT MUMBAI",
  "BIT SINDRI",
  "BMSIT&M BENGALURU",
  "CUTM PARALAKHEMUNDI",
  "CMR C.O.E. HYDERABAD",
  "DIT UNIV. DEHRADUN",
  "GEC BHUBANESWAR",
  "GITA BHUBANESWAR",
  "GMR INST. OF TECH RAJAM",
  "GCT COIMBATORE",
  "HALDIA INST. OF TECH",
  "IIPE VISAKHAPATNAM",
  "IITRAM AHMEDABAD",
  "INTEGRAL UNIV. LUCKNOW",
  "IIIT BHUBANESWAR",
  "JUIT SOLAN",
  "JSSATE NOIDA",
  "K. J. SOMAIYA C.O.E. MUMBAI",
  "KURUKSHETRA UNIV.",
  "LBRCE",
  "LNCT BHOPAL",
  "MITS MADANAPALLE",
  "MAIT DELHI",
  "MSU BARODA",
  "MAHARSHI DAYANAND UNIV.",
  "MALLA REDDY C.O.E.",
  "NARULA INST. OF TECH KOLKATA",
  "PES C.O.E. MANDYA",
  "PADMASHEE DR. D. Y. PATIL VIDYAPEETH",
  "PONDICHERRY ENGG. COLLEGE",
  "PVPSIT",
  "MIT MANIPAL",
  "IIM AHMEDABAD",
  "IIM BANGALORE",
  "IIM KOZHIKODE",
  "IIT DELHI (DMS)",
  "IIM CALCUTTA",
  "IIM LUCKNOW",
  "NITIE MUMBAI",
  "IIM INDORE",
  "XLRI JAMSHEDPUR",
  "IIT BOMBAY (SJMSOM)",
  "MDI GURGAON",
  "IIM ROHTAK",
  "SIBM PUNE",
  "IIM RAIPUR",
  "IIFT DELHI",
  "IIT MADRAS (DOMS)",
  "IIM RANCHI",
  "IIT ROORKEE (DOMS)",
  "IIT KHARAGPUR (VGSoM)",
  "SPJIMR MUMBAI",
  "NMIMS MUMBAI",
  "IIM UDAIPUR",
  "IIM KASHIPUR",
  "IIM SHILLONG",
  "JMI NEW DELHI",
  "IIM VISAKHAPATNAM",
  "IIM TIRUCHIRAPPALLI",
  "AMRITA VISHWA VIDYAPEETHAM",
  "AMITY UNIV. NOIDA",
  "IIT KANPUR (IME)",
  "IIM NAGPUR",
  "MICA AHMEDABAD",
  "IIM BODH GAYA",
  "GREAT LAKES CHENNAI",
  "IMT GHAZIABAD",
  "CHANDIGARH UNIV.",
  "GIM GOA",
  "LPU JALANDHAR",
  "ICFAI HYDERABAD",
  "IMI DELHI",
  "UPES DEHRADUN",
  "IIM JAMMU",
  "XIMB BHUBANESWAR",
  "TIET PATIALA (LMTSOM)",
  "JAIPURIA NOIDA",
  "IIT (ISM) DHANBAD",
  "IIM AMRITSAR",
  "BHU VARANASI (FMS)",
  "IRMA ANAND",
  "IIM SAMBALPUR",
  "NIT TRICHY (DOMS)",
  "GREAT LAKES GURGAON",
  "FORE SCHOOL OF MGMT",
  "CHITKARA UNIV.",
  "NIRMA UNIV. AHMEDABAD",
  "IMI KOLKATA",
  "IIM SIRMAUR",
  "TAPMI MANIPAL",
  "GRAPHIC ERA UNIV.",
  "CHRIST UNIV.",
  "IMI BHUBANESWAR",
  "SOA BHUBANESWAR",
  "K J SOMAIYA INST. MUMBAI",
  "BIMTECH GREATER NOIDA",
  "GGSIPU DELHI",
  "LIBA CHENNAI",
  "KIIT BHUBANESWAR",
  "MNIT JAIPUR",
  "ANNA UNIV. CHENNAI",
  "AMU ALIGARH",
  "ALLIANCE UNIV. BANGALORE",
  "JAIPURIA LUCKNOW",
  "MANIPAL UNIV. JAIPUR",
  "SAVEETHA INST. CHENNAI",
  "NIT CALICUT (SM)",
  "JAIN UNIV. BANGALORE",
  "JAMIA HAMDARD DELHI",
  "KLEF UNIV.",
  "PSG C.O.E. COIMBATORE",
  "CUSAT KOCHI",
  "TSM MADURAI",
  "BML MUNJAL UNIV. GURGAON",
  "WELINGKAR MUMBAI",
  "IIIT GWALIOR",
  "BBAU LUCKNOW",
  "JIMS DELHI",
  "NDIM DELHI",
  "PDEU GANDHINAGAR",
  "BIT RANCHI",
  "NIBM PUNE",
  "PANJAB UNIVERSITY (UBS)",
  "RAJAGIRI BUSINESS SCHOOL",
  "BIM TRICHY",
  "TEZPUR UNIV.",
  "MANAGE HYDERABAD",
  "IMT HYDERABAD",
  "GALGOTIAS UNIV.",
  "KREA UNIV. CHITTOOR",
  "NIT WARANGAL (DOMS)",
  "IMI VISHAKHAPATNAM",
  "JAIPURIA INDORE",
  "LBSIM DELHI",
  "NIET BUSINESS SCHOOL",
  "GANDHI INST. OF TECH",
  "GUJARAT UNIV.",
  "GJU S&T",
  "HITS CHENNAI",
  "IIHMR UNIV. JAIPUR",
  "IILM UNIV. GURGAON",
  "IPE HYDERABAD",
  "LBSIM DELHI",
  "SHARDA UNIV.",
  "SHOOLINI UNIV.",
  "UNIV. OF ALLAHABAD",
  "UNIV. OF HYDERABAD",
  "UNIV. OF JAMMU",
  "VTU BELAGAVI",
  "AMITY UNIV. PATNA",
  "AMITY UNIV. JHARKHAND",
  "BVIMED PUNE",
  "ASIAN BUSINESS SCHOOL",
  "ASSAM DON BOSCO UNIV.",
  "ASSAM DOWN TOWN UNIV.",
  "ASTHA SCHOOL OF MGMT",
  "ACADEMY OF MARITIME EDUCATION (AMET)",
  "ACCURATE INST.",
  "ACHARYA INST. OF MGMT",
  "ACHARYAS BANGALORE B SCHOOL",
  "ACROPOLIS INDORE",
  "ADARSH INST. BANGALORE",
  "ADHIYAMAAN C.O.E.",
  "ADIKAVI NANNAYA UNIV.",
  "AL BARKAT INST. MGMT.",
  "ALARD INST. PUNE",
  "ALVAS INST. OF ENGG.",
  "AMITY UNIV. RAIPUR",
  "AMITY UNIV. MUMBAI",
  "ANNA UNIV.",
  "ANNAMALAI UNIV.",
  "APEEJAY SCHOOL OF MGMT",
  "ARAVALI C.O.E. & MGMT",
  "ARMY INST. OF MGMT (AIM) KOLKATA",
  "ARMY INST. OF MGMT TECH (AIMT)",
  "AIIMS DELHI",
  "PGIMER CHANDIGARH",
  "CMC VELLORE",
  "NIMHANS BANGALORE",
  "JIPMER PUDUCHERRY",
  "SGPGI LUCKNOW",
  "BHU VARANASI (IMS)",
  "AMRITA VISHWA VIDYAPEETHAM",
  "KMC MANIPAL",
  "MMC CHENNAI",
  "DR. D. Y. PATIL VIDYAPEETH, PUNE",
  "SAVEETHA INST. CHENNAI",
  "SCTIMST THIRUVANANTHAPURAM",
  "AIIMS RISHIKESH",
  "AIIMS BHUBANESWAR",
  "AIIMS JODHPUR",
  "VMMC & SAFDARJUNG HOSPITAL, DELHI",
  "SRM IST CHENNAI",
  "KGMU LUCKNOW",
  "SRI RAMACHANDRA INST. CHENNAI",
  "SOA BHUBANESWAR (IMS)",
  "IPGME&R KOLKATA",
  "DATTA MEGHE INST. WARDHA",
  "MAMC DELHI",
  "KIIT BHUBANESWAR (KIMS)",
  "AIIMS PATNA",
  "AMU ALIGARH (JNMC)",
  "ST. JOHN'S MEDICAL COLLEGE, BENGALURU",
  "LHMC DELHI",
  "AFMC PUNE",
  "AIIMS BHOPAL",
  "UCMS DELHI",
  "KMC MANGALORE",
  "ILBS NEW DELHI",
  "GMC&H CHANDIGARH",
  "MMU AMBALA",
  "JAMIA HAMDARD",
  "AIIMS RAIPUR",
  "JSS MEDICAL COLLEGE MYSORE",
  "DMC LUDHIANA",
  "PSG IMS&R COIMBATORE",
  "GMC TRIVANDRUM",
  "SMS MEDICAL COLLEGE JAIPUR",
  "MEDICAL COLLEGE KOLKATA",
  "GCRI AHMEDABAD",
  "M. S. RAMAIAH MEDICAL COLLEGE",
  "MGMC&RI PUDUCHERRY",
  "OMC HYDERABAD",
  "CMC LUDHIANA",
  "B.D. SHARMA UHS ROHTAK",
  "MGM MEDICAL COLLEGE NAVI MUMBAI",
  "SRI DEVRAJ URS ACADEMY KOLAR",
  "KLE ACADEMY BELAGAVI",
  "DY PATIL MEDICAL COLLEGE KOLHAPUR",
  "VINAYAKA MISSIONS SALEM",
  "MEENAKSHI ACADEMY CHENNAI",
  "MSRUAS BANGALORE",
  "JNM MEDICAL COLLEGE BELAGAVI",
  "SHARDA UNIV. SCHOOL OF MEDICINE",
  "AMITY INSTITUTE OF MEDICAL SCIENCES",
  "DY PATIL MEDICAL COLLEGE PIMPRI PUNE",
  "SUKUMAN HOSPITAL RANCHI",
  "GOVT. MEDICAL COLLEGE KOZHIKODE",
  "SETI G.S. MEDICAL COLLEGE MUMBAI",
  "GR MEDICAL COLLEGE GWALIOR",
  "B. J. MEDICAL COLLEGE AHMEDABAD",
  "IGMC SHIMLA",
  "GRANT MEDICAL COLLEGE MUMBAI",
  "MGM MEDICAL COLLEGE AURANGABAD",
  "TOPUWALA NATIONAL MEDICAL COLLEGE MUMBAI",
  "STANLEY MEDICAL COLLEGE CHENNAI",
  "SETH GORDHANDAS SUNDERDAS MEDICAL COLLEGE MUMBAI",
  "R G KAR MEDICAL COLLEGE KOLKATA",
  "MADURAI MEDICAL COLLEGE",
  "GOVT. MEDICAL COLLEGE NAGPUR",
  "RIMS IMPHAL",
  "GOVT. MEDICAL COLLEGE PATIALA",
  "MAHATMA GANDHI MEDICAL COLLEGE INDORE",
  "GOVT. MEDICAL COLLEGE AMRITSAR",
  "IHM PUSA (DELHI)",
  "WGSHA MANIPAL",
  "CULINARY ACADEMY OF INDIA (CAI) HYD",
  "IHM MUMBAI",
  "IHM AURANGABAD",
  "ICI TIRUPATI",
  "ICI NOIDA",
  "SSCA PUNE",
  "OCLD (THE OBEROI)",
  "IICA NEW DELHI",
  "ISH GURGAON",
  "BCIHMCT DELHI",
  "DR. AMBEDKAR IHM CHANDIGARH",
  "AIHMCT BANGALURU",
  "IHM KOLKATA",
  "IHM GANDHINAGAR",
  "IHM HYDERABAD",
  "IHM CHENNAI",
  "IHM BANGALORE",
  "CHEF IBCA NEW DELHI",
  "IICCM PUNE",
  "PALATE CULINARY ACADEMY MUMBAI",
  "MIHMCT CHENNAI",
  "ORIENTAL SCHOOL OF HM",
  "NIPS SCHOOL OF HM KOLKATA",
  "IHM GOA",
  "IHM LUCKNOW",
  "IHM SHILLONG",
  "IHM BHOPAL",
  "IHM AHMEDABAD",
  "IHM JAIPUR",
  "IHM PATNA",
  "IHM BHUBANESWAR",
  "IHM GURDASPUR",
  "IHM RANCHI",
  "IHM VARANASI",
  "IHM SHIMLA",
  "IHM GAYA",
  "IHM ALIGARH",
  "IHM ROHTAK",
  "IHM KURUKSHETRA",
  "IHM SILIGURI",
  "IHM HAMIRPUR",
  "IHM FARIDABAD",
  "IHM JODHPUR",
  "IHM DEHRADUN",
  "IHM MADURAI",
  "IHM PUDUCHERRY",
  "IHM TIRUCHIRAPPALLI",
  "IHM THIRUVANANTHAPURAM",
  "IHM GANGTOK",
] as const;

const CollegeSearchCombobox = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedValue, setSelectedValue] = useState("");
  const [isOpen, setIsOpen] = useState(false);

  // ⭐️ 1. THE ADVANCED SEARCH ALGORITHM ⭐️
  const filteredColleges = useMemo(() => {
    if (!searchTerm) {
      // If no search term, return all colleges (or top N for performance)
      return ALLOWED_COLLEGES;
    }

    // Split the search term by space, filter out empty strings, and convert to lowercase
    const searchTerms = searchTerm
      .toLowerCase()
      .split(" ")
      .filter((term) => term.length > 0);

    return ALLOWED_COLLEGES.filter((college) => {
      const lowerCollege = college.toLowerCase();

      // Check if ALL search terms are found in the college name
      // This allows users to type "iit mad" and match "IIT MADRAS"
      return searchTerms.every((term) => lowerCollege.includes(term));
    });
  }, [searchTerm]);

  const handleSelect = (college: string) => {
    setSelectedValue(college);
    setSearchTerm(college); // Set the input field to the selected college
    setIsOpen(false);
  };

  const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    setSearchTerm(e.target.value);
    setIsOpen(true); // Open the list when typing
    setSelectedValue(""); // Clear selected value while searching
  };

  // Optional: Handle keyboard navigation (Enter/Arrow keys) for better UX

  return (
    <div className="combobox-container">
      <label htmlFor="college-search">Select College:</label>
      <input
        id="college-search"
        type="text"
        value={searchTerm}
        onChange={handleInputChange}
        onFocus={() => setIsOpen(true)}
        onBlur={() => setTimeout(() => setIsOpen(false), 200)} // Delay closing to allow clicking
        placeholder="Type college name (e.g., IITM, IIMB)"
        autoComplete="off"
      />

      {isOpen && (
        <ul className="dropdown-list">
          {filteredColleges.length > 0 ? (
            filteredColleges.map((college) => (
              <li
                key={college}
                onMouseDown={() => handleSelect(college)} // Use onMouseDown to register click before onBlur fires
                className={college === selectedValue ? "selected" : ""}
              >
                {college}
              </li>
            ))
          ) : (
            <li className="no-results">
              No colleges found matching &quot;{searchTerm}&quot;
            </li>
          )}
        </ul>
      )}

      {/* Hidden input to hold the final value for form submission */}
      <input type="hidden" name="selectedCollege" value={selectedValue} />

      {/* Display current state for confirmation */}
      <p>
        Current Selection: <strong>{selectedValue || "None"}</strong>
      </p>
    </div>
  );
};

export default CollegeSearchCombobox;
